# Generated by Django 4.1.3 on 2022-12-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0002_newsclip_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Investor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("twitter_handle", models.CharField(max_length=50)),
            ],
        ),
    ]
