# Generated by Django 4.1.3 on 2022-12-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0004_company_deal_alter_investor_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="last_funding_amount",
        ),
        migrations.RemoveField(
            model_name="company",
            name="last_funding_round",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="Deal_Type",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="Object",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="Subject",
        ),
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.CharField(default="Probably Tech", max_length=200),
        ),
        migrations.AddField(
            model_name="company",
            name="location",
            field=models.CharField(default="Probably San Francisco", max_length=200),
        ),
        migrations.AddField(
            model_name="deal",
            name="company",
            field=models.ManyToManyField(to="newsapp.company"),
        ),
        migrations.AddField(
            model_name="deal",
            name="funding_round",
            field=models.CharField(
                choices=[
                    ("PS", "Pre-Seed"),
                    ("S", "Seed"),
                    ("A", "Series A"),
                    ("B", "Series B"),
                    ("C", "Series C"),
                    ("D", "Series D"),
                    ("E", "Series E"),
                ],
                default="Series A",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="investor",
            field=models.ManyToManyField(to="newsapp.investor"),
        ),
        migrations.AddField(
            model_name="deal",
            name="quarter",
            field=models.CharField(
                choices=[("Q1", "Q1"), ("Q2", "Q2"), ("Q3", "Q3"), ("Q4", "Q4")],
                default="Q1",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="year",
            field=models.CharField(default="2023", max_length=4),
        ),
    ]
